version: '3.7'

services:
  mysql:
    container_name: rs-lokalise-test-frontend-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - app-network
  node:
    container_name: rs-lokalise-test-frontend-node
    image: node
    volumes:
      - .:/srv/app
    working_dir: /srv/app
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: rs-lokalise-test-frontend-php
    volumes:
      - .:/srv/app
    networks:
      - app-network
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: rs-lokalise-test-frontend-nginx
    ports:
      - 8000:80
    networks:
      - app-network
    volumes:
      - .:/srv/app
volumes:
  mysql-volume:
networks:
  app-network:
